--- #YAML:1.0
name: Test-WWW-Mechanize-Maypole
version: 0.2
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: Test::WWW::Mechanize for Maypole
license: perl
requires:
  Class::Data::Inheritable: 0
  HTTP::Headers::Util: 0
  HTTP::Status: 0
  Maypole: 2
  Test::More: 0
  Test::WWW::Mechanize: 0
  UNIVERSAL::require: 0
  URI: 0
provides:
  Test::WWW::Mechanize::Maypole:
    file: lib/Test/WWW/Mechanize/Maypole.pm
    version: 0.2
generated_by: Module::Build version 0.2609
